bzzc supports lots of options now.

diff --git a/src/utility/bzzc b/src/utility/bzzc
--- a/src/utility/bzzc
+++ b/src/utility/bzzc
@@ -1,43 +1,102 @@
 #!/usr/bin/env bash
 
 #
-# Stop after any error
+# Help function
 #
-set -e
+function help() {
+    echo -e "Usage:\n\t$0 [-I path1:path2:...:pathN] [-b bytecode.bo] [-d debug.bdb] infile.bzz\n"
+    echo "Type 'man bzzc' for more information."
+}
 
 #
 # Check tools
 #
-command -v bzzparse >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzparse"; exit 1; }
-command -v bzzasm >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzasm"; exit 1; }
+if [[ -z $BZZPARSE ]]; then
+    command -v bzzparse >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzparse"; exit 1; }
+    BZZPARSE=bzzparse
+fi
+if [[ -z $BZZASM ]]; then
+    command -v bzzasm >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzasm"; exit 1; }
+    BZZASM=bzzasm
+fi
 command -v rev >/dev/null 2>&1 || { echo >&2 "$0: error: can't find rev"; exit 1; }
 command -v cut >/dev/null 2>&1 || { echo >&2 "$0: error: can't find cut"; exit 1; }
 
 #
 # Check command line
 #
-if [ $# -eq 1 ]; then
-    # No include path given
-    BZZ="$1"
-elif [ $# -eq 3 -a "$1" = "-I" ]; then
-    # Include path given
-    BZZ="$3"
-    export BUZZ_INCLUDE_PATH=$BUZZ_INCLUDE_PATH:$2
-else
-    # Wrong parameters
-    echo -e "Usage:\n\t$0 [-I path1:path2:...:pathN] script.bzz\n"
-    echo "Type 'man bzzc' for more information."
-    exit 1
+BZZ=""
+while (($#))
+do
+    case $1 in
+        -I|--include)
+            if [[ -n $2 ]]; then
+                export BUZZ_INCLUDE_PATH=$BUZZ_INCLUDE_PATH:$2
+            else
+                echo "$0: error: $1 expects a colon-separated list of paths"
+                echo "Type 'bzzc -h' or 'man bzzc' for more information."
+                exit 1
+            fi
+            shift 2
+        ;;
+        -b|--bytecode)
+            if [[ -n $2 ]]; then
+                BO=$2
+            else
+                echo "$0: error: $1 expects a file name"
+                echo "Type 'bzzc -h' or 'man bzzc' for more information."
+                exit 1
+            fi
+            shift 2
+        ;;
+        -d|--debug)
+            if [[ -n $2 ]]; then
+                BDB=$2
+            else
+                echo "$0: error: $1 expects a file name"
+                echo "Type 'bzzc -h' or 'man bzzc' for more information."
+                exit 1
+            fi
+            shift 2
+        ;;
+        -h|--help)
+            help
+            shift
+            exit 0
+        ;;
+        *)
+            if [[ -z $BZZ ]]; then
+                BZZ=$1
+            else
+                echo "$0: error: unrecognized option $1"
+                echo "Type 'bzzc -h' or 'man bzzc' for more information."
+                exit 1
+            fi
+            shift
+        ;;
+    esac
+done
+if [[ -z $BZZ ]]; then
+    echo "$0: error: missing script file"
+    echo "Type 'bzzc -h' or 'man bzzc' for more information."
+    exit 1    
 fi
 
 #
-# File names
+# Set file names
 #
-BASM="$(echo $BZZ | rev | cut -d. -f 2- | rev).basm"
-BO="$(echo $BZZ | rev | cut -d. -f 2- | rev).bo"
-BDBG="$(echo $BZZ | rev | cut -d. -f 2- | rev).bdbg"
+BASM=$(mktemp bzz.XXXXXX)
+if [[ -z $BO ]]; then
+    BO="$(echo $BZZ | rev | cut -d. -f 2- | rev).bo"
+fi
+if [[ -z $BDB ]]; then
+    BDB="$(echo $BZZ | rev | cut -d. -f 2- | rev).bdb"
+fi
 
 #
 # Compilation
 #
-bzzparse "$BZZ" "$BASM" && bzzasm "$BASM" "$BO" "$BDBG" && rm -f "$BASM"
+$BZZPARSE "$BZZ" "$BASM" && $BZZASM "$BASM" "$BO" "$BDB"
+RETVAL=$?
+rm -f "$BASM"
+exit $RETVAL
